
name: CI-CD

on:
  push:
    branches: ['main']
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout do Repositório
        with:
          fetch-depth: 0  # Certifique-se de pegar todo o histórico do commit

      - name: List files after checkout
        run: ls -al
        working-directory: ${{ github.workspace }}
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Construção imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            franciscoalves90/devops4devs:${{ github.sha }}
            franciscoalves90/devops4devs:latest
  
  CD:
    needs: [CI]
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        context: default
    - uses: Azure/k8s-deploy@v5
      with:
       namespace: 'myapp'
       manifests: |
        ./k8s/deploy.yaml
       images: | 
         franciscoalves90/devops4devs:${{ github.sha }}
   
