
name: CI-CD

on:
  push:
    branches: ['main']
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout do Repositório
        with:
          fetch-depth: 0  # Certifique-se de pegar todo o histórico do commit

      - name: List files after checkout
        run: ls -al
        working-directory: ${{ github.workspace }}
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Construção imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            franciscoalves90/devops4devs:${{ github.sha }}
            franciscoalves90/devops4devs:latest
  
  CD:
    needs: [CI]
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Set up Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG_DATA" > ~/.kube/config
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: List files in k8s directory
      run: ls -al ./k8s
      
    - name: Update Kubernetes deployment with new image
      run: |
        sed -i "s|franciscoalves90/devops4devs:.*|franciscoalves90/devops4devs:${{ github.sha }}|g" ./k8s/deploy.yaml
    
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v1.1.0
      with:
        args: apply -f ./k8s/deploy.yaml
    
    - name: Verify Deployment
      uses: steebchen/kubectl@v1.1.0
      with:
        args: get pods
   
