name: CI-CD

on:
  push:
    branches: ['main']
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout do Repositório
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Construção imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            franciscoalves90/devops4devs:${{ github.sha }}
            franciscoalves90/devops4devs:latest
  
  CD:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: ghostzero/kubectl@v1.28.7+k3s1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record franciscoalves90/devops4devs:${IMAGE_TAG} container=${{ github.repository }}:${{ github.sha }}
    - name: verify deployment
      uses: ghostzero/kubectl@v1.28.7+k3s1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "v1.28.7+k3s1"
      with:
        args: '"rollout status franciscoalves90/devops4devs:${IMAGE_TAG}"' 
   
