name: CI-CD

on:
  push:
    branches: ['main']
  workflow_dispatch:
    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        name: Checkout do Repositório
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Construção imagem docker
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            franciscoalves90/devops4devs:${IMAGE_TAG}
            franciscoalves90/devops4devs:latest
   
